// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mercari/grpc-http-proxy/proxy/stub (interfaces: Stub)

// Package mock_stub is a generated GoMock package.
package mock_stub

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	grpc_http_proxy "github.com/mercari/grpc-http-proxy"
	reflection "github.com/mercari/grpc-http-proxy/proxy/reflection"
	reflect "reflect"
)

// MockStub is a mock of Stub interface
type MockStub struct {
	ctrl     *gomock.Controller
	recorder *MockStubMockRecorder
}

// MockStubMockRecorder is the mock recorder for MockStub
type MockStubMockRecorder struct {
	mock *MockStub
}

// NewMockStub creates a new mock instance
func NewMockStub(ctrl *gomock.Controller) *MockStub {
	mock := &MockStub{ctrl: ctrl}
	mock.recorder = &MockStubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStub) EXPECT() *MockStubMockRecorder {
	return m.recorder
}

// InvokeRPC mocks base method
func (m *MockStub) InvokeRPC(arg0 context.Context, arg1 reflection.MethodDescriptor, arg2 reflection.Message, arg3 *grpc_http_proxy.Metadata) (reflection.Message, error) {
	ret := m.ctrl.Call(m, "InvokeRPC", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(reflection.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokeRPC indicates an expected call of InvokeRPC
func (mr *MockStubMockRecorder) InvokeRPC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeRPC", reflect.TypeOf((*MockStub)(nil).InvokeRPC), arg0, arg1, arg2, arg3)
}
