version: 2

defaults: &defaults
  working_directory: /go/src/github.com/mercari/grpc-http-proxy

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.11-stretch

jobs:
  test:
    <<: *golang
    steps:
    - checkout
    - run:
        name: Install dependencies and vendor
        command: |
          go get -u github.com/golang/dep/cmd/dep
          make dep
    - run:
        name: Run test
        command: |
          make test
# TODO: enable coverage step after CircleCI resources are increased.
#    - run:
#        name: Run coverage
#        command: |
#          make coverage
#          bash <(curl -s https://codecov.io/bash)
  lint:
    <<: *golang
    steps:
    - checkout
    - run:
        name: Install dependencies and vendor
        command: |
          go get -u github.com/golang/dep/cmd/dep
          make dep
    - run:
        name: Run lint
        command: |
          make reviewdog
workflows:
  version: 2
  build-workflow:
    jobs:
    - test
    - lint
