version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/mercari/grpc-http-proxy

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.11-stretch
  environment:
    GO111MODULE: "on"

jobs:
  test:
    <<: *golang
    steps:
    - checkout
    - run:
        name: Install dependencies and vendor
        command: |
          make dep
    - run:
        name: Run test
        command: |
          make test
# TODO: enable coverage step after CircleCI resources are increased.
#    - run:
#        name: Run coverage
#        command: |
#          make coverage
workflows:
  version: 2
  build-workflow:
    jobs:
    - test
